actually commit code is here

diff --git a/git-monitor b/git-monitor
--- a/git-monitor
+++ b/git-monitor
@@ -1,4 +1,3 @@
-#!/usr/bin/env bash
 #!/usr/bin/env bash -x
 
 # Git Monitor
@@ -217,24 +216,60 @@ sync_state () {
     fi
 }
 
+###### Committing ######
+
+# A function to reduce git diff output to the actual changed content, and insert file line numbers.
+# Based on "https://stackoverflow.com/a/12179492/199142" by John Mellor
+diff-lines() {
+    local path=
+    local line=
+    local previous_path=
+    while read; do
+        esc=$'\033'
+        if [[ $REPLY =~ ---\ (a/)?([^[:blank:]$esc]+).* ]]; then
+            previous_path=${BASH_REMATCH[2]}
+            continue
+        elif [[ $REPLY =~ \+\+\+\ (b/)?([^[:blank:]$esc]+).* ]]; then
+            path=${BASH_REMATCH[2]}
+        elif [[ $REPLY =~ @@\ -[0-9]+(,[0-9]+)?\ \+([0-9]+)(,[0-9]+)?\ @@.* ]]; then
+            line=${BASH_REMATCH[2]}
+        elif [[ $REPLY =~ ^($esc\[[0-9;]+m)*([\ +-]) ]]; then
+            REPLY=${REPLY:0:150}           # limit the line width, so it fits in a single line in most git log outputs
+            if [[ "$path" == "/dev/null" ]]; then
+                echo "File $previous_path deleted or moved."
+                continue
+            else
+                echo "$path:$line: $REPLY"
+            fi
+            if [[ ${BASH_REMATCH[2]} != - ]]; then
+                ((line++))
+            fi
+        fi
+    done
+}
+
+make_commit_msg() {
+    MSG="$(git diff -U0 --color=always | diff-lines)"
+    LENGTH=$(echo -n "$MSG" | grep -c '^')
+
+    if [[ $LENGTH -le 10 ]]; then
+        # Use git diff as the commit msg, unless if files were added or deleted but not modified
+        if [[ -n $MSG ]]; then
+            FORMATTED_MSG="$MSG"
+        else
+            FORMATTED_MSG="New files added: $(git status -s)"
+        fi
+    else
+        FORMATTED_MSG=$(git diff --stat | grep '|')
+    fi
+    echo "$FORMATTED_MSG"
+}
+
 commit_local_changes() {
     if repo_has_changes; then
-        # commit_msg="$(git config --get branch.$branch_name.syncCommitMsg)"
-        # if [ "" == "$commit_msg" ]; then
-        #     commit_msg=${DEFAULT_AUTOCOMMIT_MSG}
-        # fi
-        # autocommit_cmd=$(echo "$AUTOCOMMIT_CMD" | sed "s/%message/$commit_msg/")
 
-        # __log_msg "Committing local changes using ${autocommit_cmd}"
-        # eval $AUTOCOMMIT_CMD
-
-        # # after autocommit, we should be clean
-        # rstate="$(git_repo_state)"
-        # if [[ ! -z "$rstate" ]]; then
-	    #     __warn_msg "Auto-commit left uncommitted changes. Please add or remove them as desired and retry."
-	    #     exit 1
-        # fi}
-        echo "blarp"
+        git add -A || warn "Cannot add all changes to commit."
+        git commit -m "$(make_commit_msg)" || error 4 "Cannot commit changes."
     fi
 }
 
@@ -257,10 +292,9 @@ wait_for_change() {
 
 do_sync() {
     check_local_state_valid
+
     msg "Syncing $TARGET"
-
     commit_local_changes
-
     fetch
 
     STATE=$(sync_state) || exit $?
