die if no git-dir or no branch

diff --git a/git-monitor b/git-monitor
--- a/git-monitor
+++ b/git-monitor
@@ -55,34 +55,40 @@ error() {
 }
 
 
-
 ######## Git Repo Operations ########
 
-get_git_dir() { git rev-parse --git-dir 2>/dev/null; }
-repo_has_changes() { git status --porcelain | grep -qE '^(\?\?|[MARC] |[ MARC][MD])*'; }
+get_git_dir() {
+    # Print the git repo directory (.git) or die
+    git rev-parse --git-dir || error $? "'$PWD' is not a git repo";
+}
 
-current_branch() {
-    # Return the current branch
-    # Or fail if no branch checked out
+
+get_current_branch() {
+    # Return the current branch or die
     if curr=$(git rev-parse --abbrev-ref HEAD 2>/dev/null); then
         if [[ -n $curr && $curr != "HEAD" ]]; then
             echo "$curr"
             return 0
         else
             # head checked out or empty branch name (should not be possible)
-            return 1
+            error 3 "'$PWD' does not have an active branch."
         fi
      else
         # Git returned error
-        return $?
+        error $? "Cannot get current branch for '$PWD'"
     fi
 }
+
+
+repo_has_changes() {
+    git status --porcelain | grep -qE '^(\?\?|[MARC] |[ MARC][MD])*';
+}
+
 
 local_state () {
     # Returns repo state as string
     local GIT_DIR
-    # Taking care to match git errorq code
-    GIT_DIR=$(get_git_dir) || error "$?" "Target '$TARGET' is not a git repo (anymore??)"
+    GIT_DIR=$(get_git_dir)
 	if [[ -f "$GIT_DIR/rebase-merge/interactive" ]]; then
 		echo "REBASE-i"
 	elif [[ -d "$GIT_DIR/rebase-merge" ]]; then
@@ -139,13 +145,15 @@ check_target() {
     fi
 
     [[ $# -eq 1 ]] || error_nowarn 1 "Need exactly 1 argument: directory to monitor"
+
+    local TARGET
     # shellcheck disable=SC2086
     TARGET="$($readlink -f $1)" || error_nowarn 128 "readlink failed?!"
     [[ -d $TARGET ]] || error 1 "Target '$TARGET' is not a directory."
 
     cd "$TARGET" || error 2 "Cannot move into target dir '$TARGET'"
-    get_git_dir || error 2 "Target '$TARGET' is not a git repo"
-    current_branch || error 3 "Target '$TARGET' does not have an active branch"
+    get_git_dir
+    get_current_branch
 }
 
 ####### Main ########
