checking local state improved

diff --git a/git-monitor b/git-monitor
--- a/git-monitor
+++ b/git-monitor
@@ -13,6 +13,8 @@
 # And a branch on that upstream remote with same name
 # Any complication on git status? Just don't do anything
 
+# Note: we DO auto-add new files. Maybe in the future use a limit on file size or number?
+
 # Requirements: bash; git; coreutils and fswatch on Mac OS
 
 # No windows support
@@ -118,41 +120,44 @@ repo_has_changes() {
 }
 
 
-local_state () {
-    # Returns repo state as string
-    local GIT_DIR
-    GIT_DIR=$(get_git_dir)
+check_local_state_valid () {
+    # Exits with an error if repo is in an unsupported state, e.g. rebasing
+    local GIT_DIR STATE
+    GIT_DIR=$(get_git_dir) || exit $?
 	if [[ -f "$GIT_DIR/rebase-merge/interactive" ]]; then
-		echo "REBASE-i"
+		STATE="rebasing"
 	elif [[ -d "$GIT_DIR/rebase-merge" ]]; then
-		echo "REBASE-m"
+		STATE="rebasing"
 	else
 		if [[ -d "$GIT_DIR/rebase-apply" ]]; then
-			echo "AM/REBASE"
+			STATE="rebasing"
 		elif [[ -f "$GIT_DIR/MERGE_HEAD" ]]; then
-			echo "MERGING"
+			STATE="merging"
 		elif [[ -f "$GIT_DIR/CHERRY_PICK_HEAD" ]]; then
-			echo "CHERRY-PICKING"
+			STATE="cherry-picking"
 		elif [[ -f "$GIT_DIR/BISECT_LOG" ]]; then
-			echo "BISECTING"
+			STATE="bisecting"
 		fi
 	fi
 	if [[ "true" = "$(git rev-parse --is-inside-git-dir 2>/dev/null)" ]]; then
 		if [[ "true" = "$(git rev-parse --is-bare-repository 2>/dev/null)" ]]; then
-			echo "|BARE"
+			STATE="a bare repo"
 		else
-			echo "|GIT_DIR"
+			STATE="a git-dir"
 		fi
 	elif [[ "true" = "$(git rev-parse --is-inside-work-tree 2>/dev/null)" ]]; then
-		git diff --no-ext-diff --quiet --exit-code || echo "|DIRTY"
-	fi
+		git diff --no-ext-diff --quiet --exit-code || STATE="Dirty"
+    fi
+    if [[ -n $STATE && "Dirty" != "$STATE" ]]; then
+        error 3 "Cannot sync '$PWD' because it is $STATE."
+    fi
 }
 
 
 sync_state () {
     # determine sync state of repository, i.e. how the remote relates to our HEAD
     local REMOTE COUNT
-    REMOTE=$(get_remote_branch)
+    REMOTE=$(get_remote_branch) || exit $?
     msg "Checking difference with '$REMOTE' for '$PWD'"
     if COUNT="$(git rev-list --count --left-right "$(get_remote_branch)"...HEAD)"; then
 
@@ -181,7 +186,6 @@ sync_state () {
     fi
 }
 
-
 ###### Detecting changes ######
 
 wait_for_change() {
@@ -195,6 +199,14 @@ wait_for_change() {
         #                = 256 + 128+ 16 + 8 + 4 + 2
         gtimeout "$TIMEOUT" fswatch --recursive --event=414 --exclude "\.git"  -1 .
     fi
+}
+
+#### Actual syncing ####
+
+do_sync() {
+    check_local_state_valid
+    sync_state
+    echo do_sync
 }
 
 #### Other ####
@@ -215,11 +227,6 @@ check_target() {
     [[ -d $TARGET ]] || error 1 "Target '$TARGET' is not a directory."
 
     cd "$TARGET" || error 2 "Cannot move into target dir '$TARGET'"
-
-    # Check some git setup things
-    # These functions will exit if things are not ok
-    get_git_dir
-    get_remote_branch
 }
 
 ####### Main ########
@@ -227,14 +234,10 @@ check_target() {
 check_target "$@" >/dev/null
 msg "Syncing $PWD"
 
-git-sync
-
 while true; do
-	changedFile=$(wait_for_change 2>/dev/null)
-	if [[ -z "$changedFile" ]];	then
-		git-sync
-	else
-		echo "Syncing for: $changedFile"
-		{ git check-ignore "$changedFile" > /dev/null; } || git-sync
-	fi
+    do_sync
+	CHANGE=$(wait_for_change 2>/dev/null)
+	if [[ -z "$CHANGE" ]];	then
+        msg "Change detected: $CHANGE"
+    fi
 done
